interface Flight {
    flight_id: string;
    source_city: string;
    destination_city: string;
    departure_date: string;
    return_date: string;
    airline: string;
    price_usd: number;
    stops: string;
    flight_duration: string;
    platform: string;
}

export const flights: Flight[] = [
    {
    flight_id: "KIWI001",
    source_city: "New York",
    destination_city: "London",
    departure_date: "2025-03-15",
    return_date: "2025-03-22",
    airline: "Qatar Airways",
    price_usd: 60,
    stops: "Direct",
    flight_duration: "7h 30m",
    platform: "Kiwi",
    },
    {
    flight_id: "SKY114",
    source_city: "New York",
    destination_city: "London",
    departure_date: "2025-03-15",
    return_date: "2025-03-22",
    airline: "British Airways",
    price_usd: 60,
    stops: "Direct",
    flight_duration: "7h 30m",
    platform: "Skyscanner",
    },
    {
    flight_id: "KIWI002",
    source_city: "Los Angeles",
    destination_city: "Tokyo",
    departure_date: "2025-04-10",
    return_date: "2025-04-20",
    airline: "Japan Airlines",
    price_usd: 780,
    stops: "1 Stop",
    flight_duration: "14h 45m",
    platform: "Kiwi",
    },
    {
    flight_id: "KIWI003",
    source_city: "Chicago",
    destination_city: "Paris",
    departure_date: "2025-05-05",
    return_date: "2025-05-15",
    airline: "Air France",
    price_usd: 620,
    stops: "Direct",
    flight_duration: "8h 50m",
    platform: "Kiwi",
    },
    {
    flight_id: "KIWI004",
    source_city: "Miami",
    destination_city: "Barcelona",
    departure_date: "2025-06-12",
    return_date: "2025-06-22",
    airline: "Iberia",
    price_usd: 540,
    stops: "1 Stop",
    flight_duration: "11h 10m",
    platform: "Kiwi",
    },
    {
    flight_id: "KIWI005",
    source_city: "San Francisco",
    destination_city: "Sydney",
    departure_date: "2025-07-01",
    return_date: "2025-07-15",
    airline: "Qantas",
    price_usd: 1250,
    stops: "Direct",
    flight_duration: "15h 30m",
    platform: "Kiwi",
    },
    {
    flight_id: "KIWI006",
    source_city: "Boston",
    destination_city: "Dublin",
    departure_date: "2025-03-25",
    return_date: "2025-04-05",
    airline: "Aer Lingus",
    price_usd: 480,
    stops: "Direct",
    flight_duration: "6h 40m",
    platform: "Kiwi",
    },
    {
    flight_id: "KIWI007",
    source_city: "Seattle",
    destination_city: "Beijing",
    departure_date: "2025-08-18",
    return_date: "2025-09-01",
    airline: "Hainan Airlines",
    price_usd: 890,
    stops: "1 Stop",
    flight_duration: "13h 20m",
    platform: "Kiwi",
    },
    {
    flight_id: "KIWI008",
    source_city: "Atlanta",
    destination_city: "Rome",
    departure_date: "2025-09-10",
    return_date: "2025-09-20",
    airline: "Delta Air Lines",
    price_usd: 710,
    stops: "Direct",
    flight_duration: "9h 45m",
    platform: "Kiwi",
    },
    {
    flight_id: "KIWI009",
    source_city: "Denver",
    destination_city: "Amsterdam",
    departure_date: "2025-10-03",
    return_date: "2025-10-14",
    airline: "KLM",
    price_usd: 670,
    stops: "1 Stop",
    flight_duration: "10h 15m",
    platform: "Kiwi",
    },
    {
    flight_id: "KIWI010",
    source_city: "Dallas",
    destination_city: "Dubai",
    departure_date: "2025-11-22",
    return_date: "2025-12-02",
    airline: "Emirates",
    price_usd: 980,
    stops: "Direct",
    flight_duration: "14h 0m",
    platform: "Kiwi",
    },
    {
    flight_id: "SKY001",
    source_city: "New York",
    destination_city: "Berlin",
    departure_date: "2025-03-18",
    return_date: "2025-03-28",
    airline: "Lufthansa",
    price_usd: 530,
    stops: "1 Stop",
    flight_duration: "9h 20m",
    platform: "Skyscanner",
    },
    {
    flight_id: "SKY002",
    source_city: "Los Angeles",
    destination_city: "Bangkok",
    departure_date: "2025-04-15",
    return_date: "2025-04-30",
    airline: "Thai Airways",
    price_usd: 920,
    stops: "1 Stop",
    flight_duration: "17h 35m",
    platform: "Skyscanner",
    },
    {
    flight_id: "SKY003",
    source_city: "Chicago",
    destination_city: "Vienna",
    departure_date: "2025-05-20",
    return_date: "2025-06-01",
    airline: "Austrian Airlines",
    price_usd: 640,
    stops: "Direct",
    flight_duration: "9h 10m",
    platform: "Skyscanner",
    },
    {
    flight_id: "SKY004",
    source_city: "Miami",
    destination_city: "Lisbon",
    departure_date: "2025-06-05",
    return_date: "2025-06-15",
    airline: "TAP Air Portugal",
    price_usd: 560,
    stops: "1 Stop",
    flight_duration: "10h 0m",
    platform: "Skyscanner",
    },
    {
    flight_id: "SKY005",
    source_city: "San Francisco",
    destination_city: "Auckland",
    departure_date: "2025-07-12",
    return_date: "2025-07-27",
    airline: "Air New Zealand",
    price_usd: 1350,
    stops: "1 Stop",
    flight_duration: "17h 50m",
    platform: "Skyscanner",
    },
    {
    flight_id: "SKY006",
    source_city: "Boston",
    destination_city: "Madrid",
    departure_date: "2025-03-30",
    return_date: "2025-04-08",
    airline: "Iberia",
    price_usd: 510,
    stops: "Direct",
    flight_duration: "7h 20m",
    platform: "Skyscanner",
    },
    {
    flight_id: "SKY007",
    source_city: "Seattle",
    destination_city: "Seoul",
    departure_date: "2025-08-05",
    return_date: "2025-08-19",
    airline: "Korean Air",
    price_usd: 870,
    stops: "Direct",
    flight_duration: "12h 0m",
    platform: "Skyscanner",
    },
    {
    flight_id: "SKY008",
    source_city: "Atlanta",
    destination_city: "Athens",
    departure_date: "2025-09-15",
    return_date: "2025-09-25",
    airline: "Aegean Airlines",
    price_usd: 690,
    stops: "1 Stop",
    flight_duration: "11h 30m",
    platform: "Skyscanner",
    },
];
